config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'cars#home'
  resources :cars, only: [:show, :new, :create, :destroy] do
    resources :rents, only: [:create]
    
  end
  post "/rents/:id/status", to: "rents#status", as: "status"
  resources :rents, only: [:index]

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  validates :model, presence: true
  validates :year, presence: true
  validates :location, presence: true
  validates :km, presence: true
  # validates :daily_rate, presence: true

  has_one_attached :picture
  has_many :rents

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model
  pg_search_scope :search_by_model_and_year_and_location,
    against: [ :model, :year, :location ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :car
  validates :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :cars
    has_many :rents_as_owner, through: :cars, class_name: "Rent", source: 'rents'
    has_many :rents
    has_many :rented_cars, through: :rents, class_name: 'Car', foreign_key: 'car_id'
    validates :user_name, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name])
  end

  after_action :verify_authorized, except: [:home, :index], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :home, unless: :skip_pundit?
  
  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :destroy]
  skip_before_action :authenticate_user!, only: :home

  def home
    if params[:query].present?
      @cars = policy_scope(Car.search_by_model_and_year_and_location(params[:query])).order(created_at: :desc)
      
    else
      @cars = policy_scope(Car).order(created_at: :desc)
    end

    @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        info_window: render_to_string(partial: "info_window", locals: { car: car }),
        image_url: helpers.asset_url("car_icon.png")
      }
    end

  end

  def show
    @rent = Rent.new(car: @car)
  end

  def new
    @car = Car.new
    authorize @car
  end

 def create
    @car = Car.new(car_params)
    @car.user = current_user
    authorize @car
    if @car.save
      redirect_to root_path, notice: "car created"
    else
      render :new
    end
  end

  def destroy
    @car.destroy
    redirect_to root_path
  end

  private

  def set_car
    @car = Car.find(params[:id])
    authorize @car
  end

  def car_params
    params.require(:car).permit(:model, :year, :km, :location, :picture, :daily_rate )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  def create
    @car = Car.find(params['car_id'])
    @rent = Rent.new(rent_params)
    @rent.car_id = params['car_id']
    @rent.user = current_user
    @rent.status = false
    authorize @rent
    if @rent.save
      redirect_to rents_path, notice: "You rented the car"
    else
      render 'cars/show'
    end
  end

  def status
    @rent = Rent.find(params[:id]) 
    authorize @rent
    if @rent.status == false
      @rent.status = true
    else 
      @rent.status = false
    end
    @rent.save
    redirect_to rents_path
  end

  def index 
    if current_user.cars.present?
      @owner = true
      @rents = current_user.rents_as_owner
    else
      @owner = false
      @rents = current_user.rents
    end

  end

  private

  def rent_params
    params.require(:rent).permit(:name, :date, :time, :car_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_info_window.html.erb
<h2><%= link_to car.model, car_path(car) %></h2>
<p><%= car.year %></p>
<%if car.picture.attached?%>
<%= cl_image_tag car.picture.key, height: 100, width: 150, crop: :limit %>
<% else %>
<%= cl_image_tag("cljrhhc1oa9pnj9hcvv1", height: 100, width: 150, crop: :limit) %>
<% end %>

app/views/cars/home.html.erb
<!-- <div class="container">
  <div class="row">
    <div class="col-12 col-lg-8">
     <% @cars.each do |car| %>
        <div class="card-product">
          <img src="https://m.extra.globo.com/incoming/17357332-fa6-89f/w488h275-PROP/capa-de-carro.jpg" />
          <div class="card-product-infos">
            <h2><%= car.model %></h2>
            <p><%= " year of fabrication :#{car.year} with #{car.km} km"  %>   <%= link_to 'view', car_path(car) %></p>
          </div>
        </div>
      <% end %>
    </div>
     <div class="col-12 col-lg-4">
      <img src="https://www.google.com/url?sa=i&url=https%3A%2F%2Fdevelopers.arcgis.com%2Fdocumentation%2Fmapping-apis-and-services%2Ftutorials%2F&psig=AOvVaw34aUrGsHoORDhRLuMQmD46&ust=1622734058466000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJjS-Myh-fACFQAAAAAdAAAAABAD">
    </div>
  </div>
</div>

 -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn2.buyacar.co.uk/sites/buyacar/files/car-parking-3000.jpg);">
  <div class="container">
    <h1><strong>Go further!</strong></h1>
    <p>Minimalism does not require you to sacrifice comfort</p>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center py-5 my-5">
    <div class="col-6 modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <h1 py-5>How it works?</h1>
      <h3 py-5>It is all about time saving.. We are an online marketplace to list or rent a car in a simple way, so that you can focus on
      what is really important: Going anywhere!</h3>
    </div>
    <div class="col-6"><img src="https://carupi.com/static/range-rover-how-it-works-0238fb341a336f923241255bdffe2b2a.webp" class="rounded" alt="..."></div>
  </div>
</div>

<div class= 'container border-bottom border-top border-warning py-5 my-5'>

  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="3500">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner align-items-center">
      <div class="carousel-item active">
        <div class="row justify-content-center">
          <div class="col-6 "><img src="https://image.freepik.com/fotos-gratis/jovem-bonito-feliz-dirigindo-carro-imagem-de-mulher-jovem-e-bonita-dirigindo-um-carro-e-sorrindo-retrato-do-carro-de-direcao-feliz-motorista-do-sexo-feminino-com-cinto-de-seguranca-na_1212-2206.jpg" class="d-block w-100 h-110" alt="..."></div>
          <div class="col-6  modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <h1 style="padding: 20px 0 0 0">The best experience I ever had!</h1>
            <p>Renata Guimarães - Rio de Janeiro/RJ</p>
            <p style="color:yellow;font-size:50px">&bigstar; &bigstar; &bigstar; &bigstar; &bigstar;</p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <div class="row justify-content-center">
          <div class="col-6"><img src="http://st.depositphotos.com/1011382/2842/i/450/depositphotos_28423123-happy-driver.jpg" class="d-block w-100" alt="..."></div>
          <div class="col-6  modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <h1 style="padding: 20px 0 0 0">I needed a simple way to make money, renting my car was the solution !.</h1>
            <p>Paula Amorim - Salvador/BA</p>
            <p style="color:yellow;font-size:50px">&bigstar; &bigstar; &bigstar; &bigstar; &bigstar;</p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <div class="row justify-content-center">
          <div class="col-6"><img src="https://image.freepik.com/free-photo/happy-young-male-driver-wheel_136930-4.jpg" class="d-block w-100" alt="..."></div>
          <div class="col-6 modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <h1 style="padding: 20px 0 0 0">It took me 15 minutes to choose and rent the car. The future is here !</h1>
            <p>Felipe Teixeira - São Paulo/SP </p>
            <p style="color:yellow;font-size:50px">&bigstar; &bigstar; &bigstar; &bigstar; &bigstar;</p>
          </div>
        </div>
      </div>
    </div>

    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
    </a>

  </div>

</div>


<div class="cont">
  <div id="core" class="row">
    <div id="sidecard" class="col-12 col-lg-8">

      
        <%= form_tag root_path(anchor:'sidemap'), method: :get do %>
        <div class= 'row'>  
          <div class= 'col-11'>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Find a car"
            %>
          </div>

          <div class= 'col-1'>
            <%= submit_tag "Search", class: "btn btn-warning" %>
          </div>
        </div>
        <% end %>
      




      <div class="cards">
        <% @cars.each do |car| %>
          <%= link_to car do %>
            <%if car.picture.attached?%>
              <div id="card_home" class="card" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path car.picture.key %>);">
            <% else %>
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path("cljrhhc1oa9pnj9hcvv1") %>);">
            <% end %>
            <div class="name mb-5">
              <%= car.model %>
            </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div id="sidemap"class="col-12 col-lg-4">
      <div id= "map" style="width: 100%; height: 760px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
</div>


<!--
        <% @cars.each do |car| %>
        <p><%= "#{car.model} - #{car.year}"%>
          <%= link_to 'delete', car_path(car), method: :delete %> |
          <%= link_to 'view', car_path(car) %>
          </p>
        <% end %>
 -->

app/views/cars/new.html.erb
<div class="col-12 col-lg-4">
  <div class="container">
    <%= simple_form_for(@car) do |f| %>
      <%= f.input :model %>
      <%= f.input :year %>
      <%= f.input :km %>
      <%= f.input :location %>
      <%= f.input :picture, as: :file %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/cars/show.html.erb
<div class="all" style="margin-top: 50px; margin-bottom: 40px;">
  <div class="card-product">
     <%if @car.picture.attached?%>
        <%= cl_image_tag @car.picture.key, height: 300, width: 400, crop: :limit %>
        <% else %>
        <%= cl_image_tag("cljrhhc1oa9pnj9hcvv1", height: 300, width: 400, crop: :limit) %>
      <% end %>
    <div class="card-product-infos">
       <h2><%= @car.model %></h2>

      <p><%= @car.km %> km </p>

      <p>Situated at: <%= @car.location %></p>

      <p>Porduced in: <%= @car.year %></p>

      <p>Price: <%= @car.daily_rate %>$ per hour</p>
    </div>
  </div>


    <div class="col-12" style="margin: 0 auto; background: white; width: 600px">
      <div class="container">
        <h3>Rent this car !</h3>
        <%= simple_form_for [@car, @rent] do |f| %>
                <%= f.input :name %>
                <%= f.input :date %>
                <%= f.input :time %>
                <%= f.submit 'Rent your car', class: 'btn btn-warning' %>
        <% end %>
        <%= link_to 'Home menu', root_path, class: 'btn btn-warning m-3' %>
      </div>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentCarAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
<!--     <div class = "container"> -->
      <%= yield %>
<!--     </div> -->
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/rents/index.html.erb
<div>
    <h1 style="text-align:center" >              My Cars                  </h1>
  <% if  @rents.empty? %>
    <h2>No rents available</h2>
  <% else  %>
  <div class="container cards pb-2">
    <% @rents.each do |rent| %>
          <div class="card" style="width: 25rem">
            <%= cl_image_tag rent.car.picture.key %>
            <div class="card-body">
              <% if @owner && !rent.status %>
                <h5 class="card-title">Client - <%=  rent.user.user_name %></h5>
                <h5 class="card-title">Mail - <%=  rent.user.email%></h5>
              <% end %>
              <h5 class="card-title">Model - <%=  rent.car.model %></h5> 
              <h5 class="card-title">Location - <%=  rent.car.location %></h5>
              <p class="card-text">Status - <%=  rent.status ? "Rent aproved" : " waiting for approval"   %></p>
              <% if @owner && !rent.status %>
              <p><%= link_to 'Approve', status_path(rent), method: :post, class: 'btn btn-primary m-3' %></p>
              <% end %>
            </div>  
          </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer pt-2">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-logo">
    <%= image_tag "car_icon.png" %>
  </div>
  <div class="footer-copyright">
    © copyright 2021 All rights reserved
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" >
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "car_icon.png" %>
    <% end %>
   <div class="title">
    RENT A CAR
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "tururu" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://avatars.githubusercontent.com/u/82628789?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Add a Car", new_car_path, class: "dropdown-item" %>
            <%= link_to "My cars", rents_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>